### PR TITLE
Feature_add_deployment_annotations

### PR DESCRIPTION
**Pull request by jgalais**
Hello,

I added Deployment annotations because it's mandatory for some applications like Reloader (https://github.com/stakater/Reloader).

Regards,
jgalais

### CODE REVIEW

**Review by sagikazarmark — CHANGES_REQUESTED** [review]
Can you please add it to `values.yaml`?

https://github.com/sagikazarmark/helm-charts/blob/master/charts/sftpgo/values.yaml#L94

**Comment by jgalais** [comment]
@sagikazarmark I added deploymentAnnotations inside values.yaml.

Regards,
jgalais

**Review by sagikazarmark — CHANGES_REQUESTED** [review]
Please update chart version

https://github.com/sagikazarmark/helm-charts/blob/master/.github/CONTRIBUTING.md

**Comment by jgalais** [comment]
I updated the chart version.

Regards,
jgalais

**Review by sagikazarmark — APPROVED** [review]

**Review by sagikazarmark — CHANGES_REQUESTED** [review]
CI is failing:


README files are not up to date (run 'make docs')

**Comment by jgalais** [comment]
> CI is failing:
> 
> README files are not up to date (run 'make docs')

I fixed that.

regards,
Jgalais

**Comment by jgalais** [comment]
Hello,

Please can you validate this PR to add this feature and avoid to your registry to add this feature. 

Regards,
Jgalais

**Review by sagikazarmark — APPROVED** [review]

**Comment by jgalais** [comment]
Please can you merge this PR on the master branch ?

Thank you,
Jgalais

**Comment by sagikazarmark** [comment]
Merged, thanks!

**Pull request merged**
