### PR TITLE
fix: Allow setting -verbose=false

### PR DESCRIPTION
**Pull request by NoUseFreak**

### CODE REVIEW

**Comment by NoUseFreak** [comment]
@sagikazarmark Any chance this one can get merged? It does not introduce any new feature, just fixes a bug where values are required to be strings

**Comment by sagikazarmark** [comment]
You might also need to rebase for CI to work properly.

**Comment by NoUseFreak** [comment]
@sagikazarmark I rebased and also fixed chart version and docs. I don't quite understand why the labeler is causing issues.

**Comment by sagikazarmark** [comment]
@NoUseFreak dunno, just ignore it. If the linter passes, I'm gonna merge it.

**Review by sagikazarmark — APPROVED** [review]

**Pull request merged**
